---
 - hosts: web  
  # vars:
  #   http_port: 80
  #   max_clients: 200
  # remote_user: root
   tasks:
     - name: copy html file
       copy:
        src: /opt/jenkins/index.html
        dest: /var/www/html/index.html
        mode: u=rw,g=r,o=r

