---
## Web Servers
- hosts: web
  roles:
    - server-common
    - webserver
#  sudo: yes
  gather_facts: no


## DB Servers
- hosts: db
  roles:
    - server-common
    - dbserver
#  sudo: yes
  gather_facts: no
